import pytest

from simple_examples import add_or_multiply, add

# Commentary: All of the following code was generated by Copilot.  Only the code above was written by me.
@pytest.mark.parametrize(
    "a,b,operator,expected",
    [
        (1, 2, "add", 3),
        (2, 2, "multiply", 4),
    ],
)
def test_add_or_multiply(a, b, operator, expected):
    assert add_or_multiply(a, b, operator) == expected


@pytest.mark.parametrize(
    "a,b,expected",
    [
        (1, 2, 3),
        (2, 2, 4),
    ],
)
def test_add(a, b, expected):
    assert add(a, b) == expected